package a;

import java.awt.Color;

import javax.swing.ImageIcon;

public class Howtomenu extends javax.swing.JFrame {

    /**
     * Creates new form Howtomenu
     */
	private static javax.swing.JFrame frame;
    public Howtomenu(javax.swing.JFrame frame) {
    	this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(695, 735));
        setSize(new java.awt.Dimension(680, 700));
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        character c = new character();
        getContentPane().add(jLabel0);
        jLabel0.setBounds(0, 0, 680, 700);
        ImageIcon icon = new ImageIcon(".\\image\\BG4.jpg");
        ImageIcon resized = PictureBuilder.resizeIcon(icon,680,700);
        jLabel2.setIcon(resized);
       
        jLabel1.setForeground(Color.red);
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 70));
        
        jLabel1.setText("How to play");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 500, 80);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 640, 100, 50);
        
        ImageIcon icon1 = new ImageIcon(character.Pic[0]);
        ImageIcon resized1 = PictureBuilder.resizeIcon(icon1,100,100);
        jLabel3.setIcon(resized1);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 200, 100, 100);

        ImageIcon icon2 = new ImageIcon(character.Pic1[0]);
        ImageIcon resized2 = PictureBuilder.resizeIcon(icon2,100,100);
        jLabel4.setIcon(resized2);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 200, 100, 100);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); 
        jLabel5.setForeground(Color.blue);
        jLabel5.setText("Runner");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 320, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20));
        jLabel6.setForeground(Color.blue);
        jLabel6.setText("Catcher");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 320, 100, 30);

        jLabel7.setForeground(Color.green);
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("if catcher can catch runner in time --catcher win");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 400, 600, 40);

        jLabel14.setForeground(Color.green);
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setText("if runner can run away from catcher over time --runner win ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 450, 600, 40);
        
        jLabel8.setForeground(Color.green);
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Can move character by keypress on keyboard");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 550, 600, 40);
        
        
        
        jLabel2.setText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 700);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          frame.setVisible(true);
    	  this.setVisible(false);   
          dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Howtomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Howtomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Howtomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Howtomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Howtomenu(frame).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    // End of variables declaration//GEN-END:variables
}
