package a;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

import a.Startmenu;

public class setserver extends javax.swing.JFrame {
	
	private String str;
	private static String text;
	
    /**
     * Creates new form Startmenu
     */
	private static javax.swing.JFrame frame;
    public setserver(javax.swing.JFrame frame, String text) {
    	this.text = text;
    	this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        jLabel1 = new javax.swing.JLabel();
        jText1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(695, 735));
        setSize(new java.awt.Dimension(880, 700));
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 640, 100, 50);
        
        
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setText("Server IP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 190,300, 40);
        
        
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText(text);
        jLabel4.setForeground(Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 316,627, 40);
        
        
        jLabel1.setText("Version 1.1.1.10.1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 680, 100, 14);
        jLabel1.getAccessibleContext().setAccessibleName("VERSIONLabel");

        

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton2.setText("Conect to Server");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 550, 341, 100);
        jButton2.getAccessibleContext().setAccessibleName("HOWButton");

        jText1.setBounds(170,230,341, 30);
        getContentPane().add(jText1);
      
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 700);
        ImageIcon icon = new ImageIcon(".\\image\\BG5.jpg");
        ImageIcon resized = a.PictureBuilder.resizeIcon(icon,680,700);
        jLabel2.setIcon(resized);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	frame.setVisible(true);
        this.setVisible(false); 
        dispose();// TODO add your handling code here:
  }

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	str = jText1.getText();
    	if(str.matches("\\d+\\.\\d+\\.\\d+\\.\\d+")){
    		Startmenu.clip.stop();
    		SocketClient s = new SocketClient(str);
        	s.setVisible(true);
            this.setVisible(false);
            frame.dispose();
    	}else {
    		JOptionPane.showMessageDialog(null, "IP addrees format isn't correct", "InfoBox: " + "warning", JOptionPane.INFORMATION_MESSAGE);
    	}  
    }//GEN-LAST:event_jButton2ActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>  
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setserver(frame, text).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jText1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
